// PAC Agent configuration — all values ported from AI Insights Generator n8n workflow

// YouTube AI Daily Brief channel
export const YOUTUBE_CHANNEL_ID = "UCKelCK4ZaO6HeEI1KQjqzWA";

// Apify actor for YouTube analytics
export const APIFY_ACTOR_ID = "h7sDV53CddomktSi5";

// YouTube search queries (22) — used by Apify actor
export const APIFY_SEARCH_QUERIES = [
  "AI lead generation for SMB",
  "ChatGPT",
  "AI tools 2026",
  "AI automation",
  "Claude AI",
  "AI for business",
  "AI tutorial",
  "AI workflow",
  "AI agents",
  "Make money with AI",
  "AI side hustle",
  "Best AI tools 2026",
  "AI news",
  "OpenAI",
  "AI productivity",
  "AI for small business",
  "AI customer service automation",
  "Small business AI strategy 2026",
  "AI automation tutorial",
  "AI agents 2026",
  "n8n automation",
  "build apps with ai",
] as const;

// Tavily search keywords (30)
export const TAVILY_KEYWORDS = [
  "AI workflow automation",
  "AI agents",
  "AI strategy",
  "AI ROI",
  "AI implementation",
  "AI adoption trends",
  "AI marketing automation",
  "AI customer communication",
  "AI sales enablement",
  "AI for small business growth",
  "AI for operations efficiency",
  "AI content automation",
  "AI for SMB customer experience",
  "AI-driven lead generation",
  "AI for productivity and team efficiency",
  "AI chatbots for SMBs",
  "AI-powered CRM automation",
  "Task decomposition",
  "Multi-agent orchestration",
  "RAG (Retrieval-Augmented Generation)",
  "Context window economy",
  "Human-in-the-loop",
  "Training-less adoption",
  "Deterministic guardrails",
  "AI copilots",
  "No-code/low-code AI",
  "Prompt engineering",
  "Voice AI / Conversational AI",
  "AI + Zapier/Make integrations",
  "Vertical AI / Industry-specific AI",
] as const;

// Tavily whitelisted domains (18)
export const TAVILY_WHITELISTED_DOMAINS = [
  "marketingaiinstitute.com",
  "deeplearning.ai",
  "blog.langchain.dev",
  "blog.llamaindex.ai",
  "community.openai.com",
  "community.anthropic.com",
  "techcrunch.com",
  "venturebeat.com",
  "zapier.com",
  "hubspot.com",
  "gartner.com",
  "producthunt.com",
  "a16z.com",
  "reddit.com",
  "huggingface.co",
  "make.com",
  "lennysnewsletter.com",
  "firstround.com",
] as const;

// TLDR AI Newsletter RSS feed
export const TLDR_RSS_URL = "https://bullrich.dev/tldr-rss/ai.rss";

// Tavily relevance score threshold
export const TAVILY_SCORE_THRESHOLD = 0.201;

// Insight categories
export const INSIGHT_CATEGORIES = [
  "infrastructure",
  "applications",
  "sales-marketing",
  "operation-efficiency",
  "ai-governance",
  "market-landscape",
  "smb",
  "research-models",
  "workforce-talent",
  "data-privacy",
] as const;

// Momentum values
export const MOMENTUM_VALUES = [
  "Emerging",
  "Accelerating",
  "Maturing",
  "Consolidating",
] as const;

// Collector limits
export const YOUTUBE_CHANNEL_LIMIT = 7;
export const APIFY_MAX_RESULTS = 10;
export const TAVILY_MAX_RESULTS = 10;

// Apify actor run body (exact params from n8n workflow)
export const APIFY_ACTOR_INPUT = {
  dateFilter: "week",
  downloadSubtitles: false,
  hasCC: false,
  hasLocation: false,
  hasSubtitles: false,
  is360: false,
  is3D: false,
  is4K: false,
  isBought: false,
  isHD: false,
  isHDR: false,
  isLive: false,
  isVR180: false,
  lengthFilter: "between420",
  maxResults: APIFY_MAX_RESULTS,
  maxResultsShorts: 0,
  preferAutoGeneratedSubtitles: false,
  saveSubsToKVS: false,
  sortingOrder: "views",
  videoType: "video",
} as const;
